In [ ]:
#distance and time are list data structures
distance=[10,15,17,26]
time=[.30,.47,.55,1.20]
speed=distance/time
print(speed)
#NOTE:list ds allows only operations on individual objects or elements
#when u trying to perform operations on all elements at a time.it does not support

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [ ]:
#create a numpy array to overcome drawbacks of list data structures
import numpy as np
distance=[[10,15],[17,26]]
time=[[.30,.47],[.55,1.20]]
np_distance=np.array(distance)
print(np_distance)
np_time=np.array(time)
print(np_time)
speed=np_distance/np_time
print(speed)
print(speed.shape)
print(speed.size)

In [ ]:
print(np_distance.ndim)
print(np_distance.shape)
print(np_distance.dtype)
print(np_distance.size)


In [ ]:
speed=np_distance/np_time
print(speed)

#Date:12/12/2024
#NUMPY HANDSON PROGRAMS
    LIST TO ARRAYS
    ARRAY INDEXING
    ARRAY SLICING
    ARRAY RESHAPING

In [ ]:
#CREATE 1 DIM ARRAY
data=[100,200,300,400] #list ds


In [ ]:
from numpy import array
data1_np=array(data)


In [ ]:
print("data created by list ds",data)
print("data created by numpy",data1_np)

In [ ]:
#properties of 1d array
print(data1_np.ndim)
print(data1_np.shape)
print(data1_np.size)
print(data1_np.dtype)

In [ ]:
#1d indexing
print(data1_np[0])
print(data1_np[-1])
print(data1_np[0:4])

In [ ]:
#create a 2 DIM array using list datastructure
data_2d_list=[[10,20],[30,40]] #nested list
print(data_2d_list)


In [ ]:

data_2d_np=array(data_2d_list)
print(data_2d_np)

In [ ]:
#properties of 2d array
print(data_2d_np.ndim)
print(data_2d_np.shape)
print(data_2d_np.size)
print(data_2d_np.dtype)

In [ ]:
#2D DATA ARRAY INDEXING
print(data_2d_np[0,0])
print(data_2d_np[1,1])
print(data_2d_np[0,1])
print(data_2d_np[1,0])
print(data_2d_np[-1,-2])
print(data_2d_np[0:2, 0:3])


In [ ]:
print(data_2d_np[1,])#display 1st row
print(data_2d_np[,2])#to overcome this drawback we need to go with slice operator

In [ ]:
print(data_2d_np[0:1,0:1])
print(data_2d_np[0:2,0:2])

In [ ]:
# 2D slicing data using Numpy
from numpy import array
data=array([[11,22,33],
           [44,55,66],
           [77,88,99]])
#extract 11 from the above data
print(data[0:1,0:1]) #before , : indicates from which row to which row
#extract 44 from the data
print(data[1:2,0:1])

In [ ]:
#extract 55 from the data
print(data[1:2,1:2])

In [ ]:
#extract 99 from the data
print(data[2:3,2:3])

In [ ]:
#extract all the rows and columns from the data
print(data[0:3,0:3])

In [ ]:
#extract 2nd row and all the elements to display
print(data[2:3,0:3]) #or data[2,:]
print(data[2,:])


In [ ]:
#extract 2nd column and all rows elements
from numpy import vstack
vdata=data[:,2]
print(vstack(vdata))
print(data[0:3,2:3])

In [ ]:
#split dataset for supervised learning algorithm as train dataset and test dataset
#first input features:split all the rows and all columns except last column
#target column as all the rows and last column

In [ ]:
from numpy import array
dataset=array([[1,2,3,8,9],
              [4,5,6,7,6],
              [7,8,9,1,2],
              [10,11,12,3,6],
              [14,15,16,17,18]])
print(dataset[0:5,0:5])

[[ 1  2  3  8  9]
 [ 4  5  6  7  6]
 [ 7  8  9  1  2]
 [10 11 12  3  6]
 [14 15 16 17 18]]


In [ ]:
#first input features:split all the rows and all columns except last column
#method 1:
print("method1\n")
print(dataset[0:5,0:4])
#method 2:
print("method2\n")
print(dataset[:,:-1])

method1

[[ 1  2  3  8]
 [ 4  5  6  7]
 [ 7  8  9  1]
 [10 11 12  3]
 [14 15 16 17]]
method2

[[ 1  2  3  8]
 [ 4  5  6  7]
 [ 7  8  9  1]
 [10 11 12  3]
 [14 15 16 17]]


In [ ]:
#target column as all the rows and last column
#traditional method
print("method1\n")
print(dataset[0:5,4:5])
#method2:
print("method2\n")
print(dataset[:,-1])


method1

[[ 9]
 [ 6]
 [ 2]
 [ 6]
 [18]]
method2

[ 9  6  2  6 18]


In [ ]:
from numpy import vstack
print(vstack(dataset[0:5,4:5]))

[[ 9]
 [ 6]
 [ 2]
 [ 6]
 [18]]


In [ ]:
#split as train data sample and test data
split=3

In [ ]:
#train data:split dataset as well as the rows from the begining to the split point
#method1
print(dataset[0:split,:])
#method2

[[1 2 3 8 9]
 [4 5 6 7 6]
 [7 8 9 1 2]]


In [ ]:
#test data: all the rows starting from the split point to the end of dimension
print(dataset[split:5,:])#

[[10 11 12  3  6]
 [14 15 16 17 18]]


In [ ]:
#reshaping array
data=array([1,2,3,4,5])
print(data.shape)

(5,)


In [ ]:
#2D array
d2_data=array([[10,20,50],
              [30,40,60]])
print(d2_data.shape)
print(d2_data.shape[0])
print(d2_data.shape[1])

(2, 3)
2
3


In [ ]:
#demo about reshape() method
from numpy import array
dataset3=array([[1,2,3],
               [4,5,6],
               [7,8,9]])


In [ ]:
#write a code to reshape dataset3 into 1 row and 9 columns using reshaping method
dataset4_reshaped=dataset3.reshape((1,9))
print(dataset4_reshaped)
print(dataset3)

[[1 2 3 4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(dataset3.shape)
print(dataset4_reshaped.shape)

(3, 3)
(1, 9)


In [ ]:
#write a code to reshape dataset3 into 9 row and 1 column using reshaping method
dataset5_reshaped=dataset.reshape((9,1))
print(dataset5_reshaped)

In [ ]:
#Qsn-1
#Create a numpy array and print array by using list L,L is already defined.
L=[2,3,46,1,6,4,767,23,98,34,23,67,55,33,87,45,23,12,98,45,3,23,56,98,87,65,45,33,22,11,79,13,48,54,17,74,38,61,93,57,83,90,13,43,55,87,13,96,77,23,65,97,2,5]
array_L=array(L)
print(array_L)

In [ ]:
#Qsn-2
#Create a numpy array with the following
'''1. Elements from 'm' to 'n'-------m&n is already defined
2. Print Only Even numbers
3. Data type is float'''
import numpy as np
m = 3
n = 201
# Create an array with elements from m to n
arr = np.arange(m, n + 1, dtype=float)
# Filter for even numbers
even_arr = arr[arr % 2 == 0]
# Print the even array
print(even_arr)


In [ ]:
#Qn-3:
'''1. Create 1 Dimension array A
2. Reshape A with 4 dimensions
        1D = 2 Elements
        2D = 3 Elements
        3D = 4 Elements
        4D = 5 Elements
2. Data type is int32
3. Display A'''
import numpy as np

# Create a 1D array A
A = np.array([1, 2, 3, 4 , 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# reshape A with 4 dimensions
A_1d = A.reshape([1, 2])
A_2d = A.reshape[3, 4, 5]
A_3d = A.reshape[6, 7, 8, 9]
A_4d = A.reshape[10, 11, 12, 13, 14]

# Set the data type to int32
A_ = A.astype('int32')

# Display A
print("1D Array A:")
print(A)




In [ ]:
# Q4:Create a numpy array using List1(List1 is already defined).
#Print the elements in reverse order by using slicing
from numpy import array
List1=[2,3,46,1,6,4,767,23,98,34,23,67,55,33,87,45,23,12,98,45,3,23,56,98,87,65,45,33,22,11,79,13,48,54,17,74,38,61,93,57,83,90,13,43,55,87,13,96,77,23,65,97,2,5]
array_List1=array(List1)
print(array_List1[::-1])


In [ ]:
# Q5:Create a numpy array by using 'm' & reshape it into 4*4 matrix.
#Print 2*2 matrix using slicing.
import numpy as np

m = np.array(range(1, 17))

matrix = np.reshape(m, (4, 4))

print("Original 4x4 Matrix:")
print(matrix)

print("\n2x2 Matrix:")
sub_matrix = matrix[0:2, 0:2]
print(sub_matrix)



In [ ]:
#Qsn-6:
'''A and B are 2 pre-defined lists.
Consider the given lists and create arrays a, b of numpy
Apply the arithmetic operators like +,-,*,/,% on them
Display the output as given in the sample output.'''
import numpy as np
A=[4,3,6,8,2,9,1,45,34,87,22,98,34,62,71,23,67,37,82,45,11,23,37,47,98]
B=[5,8,67,43,22,54,33,12,36,73,89,32,12,67,44,87,33,65,22,89,22,39,22,44,33]
a=np.array(A)
b=np.array(B)
print("Addition:",a+b)
print("Subraction:",a-b)
print("Multiplication:",a*b)
print("Division:",a/b)
print("Modulo:",a%b)


In [ ]:
#Q7:Create a numpy array using 'm'.convert 'm' into the dimension 3X3X3 using arange()
#Create a View with second row of each element of 0th dimension
#Display the View
m=27


## TOPIC:NUMPY
#1.limitation of array arithmetic
#2.array broad casting
#3.broadcasting in numpy
#4.limitations of broadcasting

In [ ]:
#limitation of arithmetic using array
from numpy import array
a=[1,2,3]
b=[4,5,6]
c=a+b
print(c)

In [ ]:
#array broadcasting
x=array([1,2,3,4,5])
print(x)

In [ ]:
y=array([4,5,6,7,8])
print(y)

In [ ]:
#broadcast
res=x+y
print(res)

In [ ]:
#broadcast scalar to 1D Array
A=array([[1,2,3],
        [4,5,6],
        [8,8,9]])
print(A)
B=2
#broadcast
c=A*B
print(c)

In [ ]:
#limitation of broadcasting
g=array([[1,2,3],
         [4,5,6]])
h=array([1,2])
print(g.shape)
print(h.shape)
res=g+h
print(res)

In [ ]:
#note:broadcasting is possible only when shape of each dimension in the arrays are equal or one has dimension size is 1
import numpy as np
a=np.array([[3,3.2],[3.5,3.6]])
b=np.array([118.4,135.2])
x=np.linalg.solve(a,b)
print(x)

[16. 22.]


# Chapter-6:Types of Matrices
1.Square matrix
2.Symmetric Matrix
3.Triangular Matrix

In [ ]:
from numpy import array
#define square 2x2 matrix
list1=[[501,"venkat"],[502,"anu"]]
'''A=array([[1,2],
        [3,4]])'''
A=array([list1])
print(list1)
print(A)
print(A.ndim)
print(A.shape)
print(A.size)
print(A.dtype)


[[501, 'venkat'], [502, 'anu']]
[[['501' 'venkat']
  ['502' 'anu']]]
3
(1, 2, 2)
4
<U21


#2.Symmetric Matrix

In [ ]:
A=array([[1,2,3],
         [2,1,2],
         [3,2,1]])
print(A)
#transpose A
Aprime = A.T
print(Aprime)

[[1 2 3]
 [2 1 2]
 [3 2 1]]
[[1 2 3]
 [2 1 2]
 [3 2 1]]


In [ ]:
from numpy import array
A=array([[4,5,6],
        [5,7,8],
        [6,8,4]])
print(A)
print(A.T)

[[4 5 6]
 [5 7 8]
 [6 8 4]]
[[4 5 6]
 [5 7 8]
 [6 8 4]]


#Pandas
#Date:4/01/2025

In [ ]:
import pandas as pd
import numpy as np
import os
#create series with list
list1=[1,2,3,4]
s=pd.Series(list1)
print(s)

print("\n")

#create series without usage of list data structure
s1=pd.Series(["sreeya","shresta","supritha","mahitha","divya"])
print(s1)

#create series along with index in customised manner
s2=pd.Series(["sreeya","shresta","supritha","mahitha","divya"],index=[2,3,4,5,6])
print(s2)

0    1
1    2
2    3
3    4
dtype: int64


0      sreeya
1     shresta
2    supritha
3     mahitha
4       divya
dtype: object
2      sreeya
3     shresta
4    supritha
5     mahitha
6       divya
dtype: object


In [ ]:
#data frame is the set of series become data frame
#data frame is 2D data which means that its look like table
import pandas as pd



In [ ]:
df1=pd.DataFrame(columns=["NAME","COURSE","LOCATION"])
print(df1)
df1.loc[0]=["DR.VENKAT","AIML","HYDERABAD"]
df1.loc[1]=["Mr.Tharun","AWS","HYDERABAD"]
df1.loc[2]=["Mrs.Sindhuja","FSJ","HYDERABAD"]
print(df1)

Empty DataFrame
Columns: [NAME, COURSE, LOCATION]
Index: []
           NAME COURSE   LOCATION
0     DR.VENKAT   AIML  HYDERABAD
1     Mr.Tharun    AWS  HYDERABAD
2  Mrs.Sindhuja    FSJ  HYDERABAD


In [ ]:
import pandas as pd
df4=pd.DataFrame(columns=["NAME","COURSE","LOCATION","DURATION"])
print(df4)
df4.loc[0]=["SREEYA","DATASCIENCE","HYDERABAD","5 MONTHS"]
df4.loc[1]=["SHRESTA","CYBERSECURITY","HYDERABAD","5 MONTHS"]
df4.loc[2]=["SUPRITHA","JAVA FULLSTACK","HYDERABAD","5 MONTHS"]
df4.loc[3]=["DEEKSHITHA","PYTHON FULLSTACK","HYDERABAD","5 MONTHS"]
df4.loc[4]=["DIVYA","SELENIUM","HYDERABAD","5 MONTHS"]
print(df4)

Empty DataFrame
Columns: [NAME, COURSE, LOCATION, DURATION]
Index: []
         NAME            COURSE   LOCATION  DURATION
0      SREEYA       DATASCIENCE  HYDERABAD  5 MONTHS
1     SHRESTA     CYBERSECURITY  HYDERABAD  5 MONTHS
2    SUPRITHA    JAVA FULLSTACK  HYDERABAD  5 MONTHS
3  DEEKSHITHA  PYTHON FULLSTACK  HYDERABAD  5 MONTHS
4       DIVYA          SELENIUM  HYDERABAD  5 MONTHS


In [ ]:
#create a dataframe from a list of nested values
list2=[["SRINI","IOT","HYD"],["MANISH","EMBEDDED SYSTEMS","HYD"]]
df2=pd.DataFrame(list2,columns=["NAME","COURSE","LOCATION"])
print(df2)

     NAME            COURSE LOCATION
0   SRINI               IOT      HYD
1  MANISH  EMBEDDED SYSTEMS      HYD


In [ ]:
#create a dataframe using numpy array with arrange() and reshape()
import numpy as np
a=np.arange(15).reshape(3,5)
print(a)
df3=pd.DataFrame(columns=["A","B","C","D","E","F"])
print(df3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
Empty DataFrame
Columns: [A, B, C, D, E, F]
Index: []


In [ ]:
df3.T

Empty DataFrame
Columns: []
Index: [A, B, C, D, E, F]

In [ ]:
#imort local machine dataset into colab notebook
import io
import pandas as pd
from google.colab import files
uploaded=files.upload()
df5=pd.read_csv(io.BytesIO(uploaded['MarketingData1.csv']))
print(df5)

In [ ]:
df5.head()

In [ ]:
#bottom 5 records
df5.tail()

In [ ]:
#display no of columns in a data frame
df5.shape[1]

In [ ]:
#display no of samples in data frame
df5.shape[0]

In [ ]:
#display information about metadata about dataframe
print(df5.info())

In [ ]:
#display summary of statistics--IQR(interquartile range)
print(df5.describe())

In [ ]:
#display top 50 samples
print(df5.head(50))

In [ ]:
#display top 50 Visitors column
df5.Visitors.head(50)

In [ ]:
#display top 15 samples related to Marketing Spend.
df5['Marketing Spend'].head(15)

In [ ]:
#display top 15 samples related to Revenue generated.
df5["Revenue"].head(15)

In [ ]:
#display 3 columns data from visitors,revenue,marketing spend.
df5[["Visitors","Revenue","Marketing Spend"]]

In [ ]:
#find the sum of values in visitors column
print("sum of visitors:\n",df5.Visitors.sum())

In [ ]:
#find the sum of revenue in revenue column
print("sum of revenue:\n",df5["Revenue"].sum())

In [ ]:
#find the sum of marketing spend
print("sum of marketing spend:\n",df5["Marketing Spend"].sum())

In [ ]:
#row filtering
#display rows from 0 to 4
df5[0:5]

In [ ]:
#display rows from 0 to 8


In [ ]:
def head_cust(df):
  print(df[0:5])

In [ ]:
#call head_cust(df)
head_cust(df5)

In [ ]:
def tail_cust(df):
  print(df[-5:])

In [ ]:
tail_cust(df5)

In [ ]:
#select all the data when the day is Monday
print(df5[df5.Day_Name=="Monday"])

In [ ]:
#display samples where day names are saturday,sunday
print(df5[(df5.Day_Name=="Saturday")|(df5.Day_Name=="Sunday")])

In [ ]:
#display the samples from the dataframe where marketing spend is greater than 1000 and promo is equal to no promo
print(df5[(df5['Marketing Spend'] > 1000) & (df5['Promo'] == 'No Promo')])

In [ ]:
#display the samples from the df5 where revenue is >2000 and marketing spend is > 1000
print(df5[(df5['Revenue'] > 2000) & (df5['Marketing Spend'] >1000)])

In [ ]:
#display df5 samples in sorted order with date column
print(df5.sort_values(by="Date",ascending=False).head(10))

In [ ]:
#display line graph age vs weight using matplotlib
import matplotlib.pyplot as plt
age=[20,21,19,22,23,25,30]
weight=[45,20,40,52,25,60,70]
plt.plot(age,weight)
plt.show()

In [ ]:
#use or apply xlabel and ylabel and title for the above graph
import matplotlib.pyplot as plt
age=[20,21,19,22,23,25,30]
weight=[45,20,40,52,25,60,25]
plt.plot(age,weight)
plt.xlabel("AGE OF THE PERSON")
plt.ylabel("WEIGHT OF THE PERSON")
plt.title("AGE VS WEIGHT")
plt.show()

In [ ]:
import matplotlib.pyplot as plt
age=[20,21,22,23,25,30]
weight=[45,46,47,52,55,60]
plt.plot(age,weight)
plt.xlabel("AGE OF THE PERSON")
plt.ylabel("WEIGHT OF THE PERSON")
plt.title("AGE VS WEIGHT")
plt.show()

In [ ]:
#to the above scenario additionally take height of the candidate and display x-axis is age  and y and z axis on y label
import matplotlib.pyplot as plt
age=[20,21,19,22,23,25,30]
weight=[45,20,40,52,55,60]
height=[150,155,160,165,170,175]
plt.plot(age,weight)
plt.plot(age,height)
plt.xlabel("AGE OF THE PERSON")
plt.ylabel("WEIGHT and HEIGHT OF THE PERSON")
plt.title("AGE VS WEIGHT vs HEIGHT")
plt.show()

In [ ]:
#add the legend to the above graph: legend is used to indicate which color is for what feature


In [ ]:
#color and plot representation
import matplotlib.pyplot as plt

age=[20,21,22,23,25,30]

weight=[45,46,47,52,55,60]

height=[150,155, 160, 165, 170, 175]

plt.plot(age, weight, label="weight", color="m") #age vs weight

plt.plot(age,height, label="height", color="c") #age vs height

plt.xlabel("AGE OF THE PERSON")

plt.ylabel("Weight & Height of the PERSON")

plt.title("AGE VS WEIGHT vs HEIGHT")

plt.legend(["WEIGHT", "HEIGHT"])

plt.show()

In [ ]:
#use markers to specify intersect point in the graph
import matplotlib.pyplot as plt

age=[20,21,22,23,25,30]

weight=[45,46,47,52,55,60]

height=[150,155, 160, 165, 170, 175]

plt.plot(age, weight, label="weight", color="m",marker="*") #age vs weight
plt.plot(age,height, label="height", color="c",marker="p") #age vs height
plt.xlabel("AGE OF THE PERSON")
plt.ylabel("Weight & Height of the PERSON")
plt.title("AGE VS WEIGHT vs HEIGHT")
plt.legend(["WEIGHT", "HEIGHT"])

plt.show()

In [ ]:
#line styles
import matplotlib.pyplot as plt

age=[20,21,22,23,25,30]
weight=[45,46,47,52,55,60]
height=[150,155, 160, 165, 170, 175]

plt.plot(age, weight, label="weight", color="m",marker="*",linestyle="--") #age vs weight
plt.plot(age,height, label="height", color="c",marker="p",linestyle="-.") #age vs height
plt.xlabel("AGE OF THE PERSON")
plt.ylabel("Weight & Height of the PERSON")
plt.title("AGE VS WEIGHT vs HEIGHT")
plt.legend(["WEIGHT", "HEIGHT"])

plt.show()

In [ ]:
#line width in graph
#use markers to specify intersect point in the graph
import matplotlib.pyplot as plt

age=[20,21,22,23,25,30]

weight=[45,46,47,52,55,60]

height=[150,155, 160, 165, 170, 175]

plt.plot(age, weight, label="weight", color="m",marker="*",linestyle="--",linewidth=5) #age vs weight
plt.plot(age,height, label="height", color="c",marker="p",linestyle="-.",linewidth=2) #age vs height
plt.xlabel("AGE OF THE PERSON")
plt.ylabel("Weight & Height of the PERSON")
plt.title("AGE VS WEIGHT vs HEIGHT")
plt.legend(["WEIGHT", "HEIGHT"])

plt.show()

In [ ]:
#use grid() function to make entire rows and columns
#line width in graph
#use markers to specify intersect point in the graph
import matplotlib.pyplot as plt

age=[20,21,22,23,25,30]

weight=[45,46,47,52,55,60]

height=[150,155, 160, 165, 170, 175]

plt.plot(age, weight, label="weight", color="m",marker="*",linestyle="--",linewidth=5) #age vs weight
plt.plot(age,height, label="height", color="r",marker="p",linestyle="-.",linewidth=2) #age vs height
plt.xlabel("AGE OF THE PERSON")
plt.ylabel("Weight & Height of the PERSON")
plt.title("AGE VS WEIGHT vs HEIGHT")
plt.legend(["WEIGHT", "HEIGHT"])
plt.grid(linewidth=2,color='c',linestyle=':')
plt.show()

#pie chart:
where  the slices will be ordered and plotted counter clock wise


In [ ]:
branches=["CSE","ECE","EEE","MECH","CIVIL","AIML","DSML","IOT"]
pass_percentages=[80,82,85,65,55,75,78,59,82]
plt.pie(pass_percentages,labels=branches,autocpt='%1.1f%%')
#plt.legend()
plt.show()

#DATA COLLECTION METHODS FOR DATA ANALYTICS

In [ ]:
#USING GOOGLE.COLAB
#Dataset is exist in local hard disk drive
#following packages and modules required to import datasets
#import .csv files
import pandas as pd
from google.colab import files

In [ ]:
import io
uploaded=files.upload() # import local file to colab file


In [ ]:
df=pd.read_csv(io.StringIO(uploaded['Salaries1.csv'].decode('utf-8')))

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.describe()

In [ ]:
df.shape[0]
df.shape[1]

In [ ]:
df.columns

In [ ]:
df.index

In [ ]:
df.dtypes

In [ ]:
df['salary'].mean()
df['salary'].mode()

In [ ]:
df['salary'].value_counts().tail(1)

In [ ]:
df['salary'].sum()

In [ ]:
df['salary'].min()

In [ ]:
df['salary'].max()

In [ ]:
df.groupby('service')['salary'].sum()
print(df.salary)
print(df.service)

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Salary_Data.csv")

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Customer_Churn_Data.xlsx",sheet_name="Data for DSBA",usecols=['AccountID','Churn','Tenure','City_Tier'])

In [ ]:
print(df.head())

#EXTRACT DATA FROM THE TABLE WHICH IS HOSTED OVER WEB

In [ ]:
#read_table()
df=pd.read_table('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv',sep="\t")
print(df.head())

In [ ]:
#ex2
df2=pd.read_table('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv',sep="|")
print(df2.head())

#EXTRACT DATA FROM MYSQL DATABASE AND CONVERT INTO DATA FRAME
NOTE:colab tool cannot communicate with mysql local database
use pycharm to extract data from mysql

In [ ]:
!pip install pymysql
import pymysql
import pandas as pd

In [ ]:
db_con=pymysql.connect(host="localhost",user="root",password="sree@0809")
db_cus=db_con.cursor()
db_cus.execute("select * from student_details")
table_data=db_cus.fetchall()
df=pd.DataFrame(table_data)
print(df.head())

#Extract Data from Mongodb and convert into dataframe

In [ ]:
import pymongo
import pandas as pd
conn=pymongo.MongoClient("mongodb://localhost:27017/")
db=conn.ACT_DB
coll=db.STUDENT_DETAILS
df=pd.DataFrame(list(coll.find()))
print(df.head())

# DATA EXTRACTION FROM HTML PAGE AND CONVERT AS DATA FRAME


In [ ]:
import pandas as pd
data_url="https://www.w3schools.com/html/html_tables.asp"
#parse the html tables and return as a list of dat frames
html_tables=pd.read_html(data_url)
#first table need to shown from the webpage
f_table=html_tables[0]
#print the datetype
print(type(f_table))
print(f_table)

In [ ]:
#pandas
import pandas as pd
data_url="https://testautomationpractice.blogspot.com/"
tables=pd.read_html(data_url)
#first table need to shown from the webpage
f_table=tables[0]
f_table1=tables[1]
f_table2=tables[2]
#print the datetype
print(type(f_table))
print(type(f_table1))
print(type(f_table2))
print(f_table)
print(f_table1)
print(f_table2)

In [ ]:
import pandas as pd
data_url="https://www.runnersworld.com/races-places/a20823734/these-are-the-worlds-fastest-marathoners-and-marathon-courses/"
#parse the html tables and return as list of dataframes
html_tables=pd.read_html(data_url,header=0)
#first table need to shown from the webpage
f_table=html_tables[2]
#print the datatype
print(type(f_table))
print(f_table)

#DATA EXTRACTION FROM API JSON

In [ ]:
import requests as req
import pandas as pd
import json


res = req.get('https://jsonplaceholder.org/users')
data = res.text

df = pd.DataFrame(json.loads(data))
print(df.tail())

In [ ]:
# Use DataFrame.from_dict()
# To convert JSON to DataFrame
import pandas as pd
import json
from pandas import json_normalize
json_string = '{ "Courses": "Spark", "Fee": 22000,"Duration":"40Days"}'
data = json.loads(json_string)

# Use pandas.DataFrame.from_dict()
# To Convert JSON to DataFrame
df2 = pd.DataFrame.from_dict(data, orient="index")
print(df2)

In [ ]:
import pandas as pd
import json
from pandas import json_normalize
data = '''
{
"technologies":
         [
         { "Courses": "Spark", "Fee": 22000,"Duration":"40Days"},
         { "Courses": "PySpark","Fee": 25000,"Duration":"60Days"},
         { "Courses": "Hadoop", "Fee": 23000,"Duration":"50Days"}
         ],
"status": ["ok"]
}
'''
print("Create JSON data:\n", data)

In [ ]:
# Use json_normalize() to convert JSON to DataFrame
dict = json.loads(data)
df2 = json_normalize(dict['technologies'])
print("After converting JSON data to DataFrame:\n", df2)

In [ ]:
import pandas as pd

url = "https://archive-api.open-meteo.com/v1/era5?latitude=52.52" +\
  	"&longitude=13.41&start_date=2021-01-01&end_date=2021-12-31&hourly=temperature_2m"

df=pd.read_json(url)
df.head()

In [ ]:
import pandas as pd
url="https://dummyjson.com/products"
df=pd.read_json(url)

In [ ]:
import numpy as np
import pandas as pd